#!/usr/bin/env node
import { createRequire } from 'node:module';
import { readFile, mkdir, rmdir, chmod } from 'node:fs/promises';
import { resolve, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes, randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { check, hash, hx, digest, le, quota, template, accountsFor, queryIx, commitIx, validatePlan, assertPreparedAction, reconcile, decodeIx } from './abi.mjs';
import { save, read, exists, privateDir, stage, recover, sendSetup, budgeted, validateWire } from './wire.mjs';
const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),LOCAL=resolve(ROOT,'.local'),TOKEN='TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',PROOF='ZkE1Gama1Proof11111111111111111111111111111';
const execute=promisify(execFile);
export function parse(args){const [command,...rest]=args,o={};check(['prepare','approve-query','approve-payment','observe','recover'].includes(command),'Expected prepare, approve-query, approve-payment, observe or recover');const known=['instance','operation','admin-keyfile','owner-keyfile','amount','product','expiry-slot','label','provisioned-directory','role','submit'];for(let i=0;i<rest.length;i+=2){const key=rest[i]?.slice(2);check(rest[i]?.startsWith('--')&&known.includes(key)&&rest[i+1]&&!rest[i+1].startsWith('--')&&!(key in o),'Expected unique --option value');o[key]=rest[i+1];}check(o.instance&&o.operation,'Require instance and operation');check(o.submit===undefined||['yes','no'].includes(o.submit),'Submit must be yes/no');const signing=['prepare','approve-query','approve-payment'].includes(command);check(signing?o['admin-keyfile']&&o['owner-keyfile']:!o['admin-keyfile']&&!o['owner-keyfile'],'Explicit owner/admin only for preparation/approval');if(command==='prepare'){check(/^[1-9][0-9]*$/.test(o.amount??'')&&BigInt(o.amount)<1n<<48n,'Positive amount below 2^48 required');check(/^[0-9a-f]{64}$/.test(o.product??''),'Exact32 product required');check(/^(0|[1-9][0-9]*)$/.test(o['expiry-slot']??'')&&BigInt(o['expiry-slot'])<1n<<64n,'Canonical u64 expiry required');check(/^[a-z0-9-]{1,64}$/.test(o.label??''),'Label required');}else for(const key of ['amount','product','expiry-slot','label','provisioned-directory'])check(!o[key],`${key} only valid for prepare`);check(command==='recover'?['query','commit'].includes(o.role):!o.role,'Recovery requires query/commit role');if(['prepare','observe'].includes(command))check(o.submit===undefined,'Submit invalid for prepare/observe');return {command,o};}
function local(path){const p=resolve(path);check(p.startsWith(LOCAL+sep),'Runtime files must remain beneath repository .local');return p;}
async function version(require,name,wanted){let path=dirname(require.resolve(name));for(let i=0;i<8;i++,path=dirname(path)){try{const p=JSON.parse(await readFile(resolve(path,'package.json')));if(p.name===name){check(p.version===wanted,`Require pinned ${name}@${wanted}`);return;}}catch(e){if(e.message.startsWith('Require pinned'))throw e;}}throw Error(`Cannot verify package ${name}`);}
export async function connect(instance,{adminPath,ownerPath}={}){
  const require=createRequire(resolve(instance.moduleRoot,'package.json'));
  for(const [name,v] of [['@solana/web3.js','1.99.0'],['@anchor-lang/core','1.2.0'],['@arcium-hq/client','0.15.0'],['bn.js','5.2.5']])await version(require,name,v);
  const w=require('@solana/web3.js'),anchor=require('@anchor-lang/core'),ar=require('@arcium-hq/client'),BN=require('bn.js'),bs=require('bs58'),bs58=bs.default??bs,pk=x=>new w.PublicKey(x),pda=(program,...seeds)=>w.PublicKey.findProgramAddressSync(seeds,pk(program))[0];
  const url=new URL(instance.endpoint);check(url.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(url.hostname)&&!url.username&&!url.password&&!url.search&&!url.hash,'Only local unauthenticated RPC allowed');
  const rpc=new w.Connection(instance.endpoint,{commitment:'confirmed',disableRetryOnRateLimit:true,fetch:(u,o)=>fetch(u,{...o,redirect:'error'})});
  check((await rpc.getVersion())['solana-core']==='4.3.0','Require Agave4.3');check(await rpc.getGenesisHash()===instance.descriptor.genesisHash,'Wrong instance ledger');
  const d=instance.descriptor;check(d.profile==='local-custom-policy-v1'&&d.cipher==='cspl-rescue-scalar253-v1'&&pda(d.programs.policy,Buffer.from('quota')).toBase58()===d.quota,'Unsupported deployment');
  const signer=async path=>w.Keypair.fromSecretKey(Uint8Array.from(await read(local(path))));
  const payer=adminPath?await signer(adminPath):null,owner=ownerPath?await signer(ownerPath):null;
  const wallet=payer?new anchor.Wallet(payer):{publicKey:pk(d.programs.auth),signTransaction:async()=>{throw Error('Keyless');},signAllTransactions:async()=>{throw Error('Keyless');}};
  const provider=new anchor.AnchorProvider(rpc,wallet,{commitment:'confirmed',preflightCommitment:'confirmed'}),program=new anchor.Program(JSON.parse(await readFile(instance.idl)),provider);
  check(program.programId.toBase58()===d.programs.auth,'Wrong IDL authority');
  return {instance,w,anchor,ar,BN,bs58,pk,pda,rpc,payer,owner,provider,program,sequence:0};
}
async function readQuota(c,minContextSlot=0){const r=await c.rpc.getAccountInfoAndContext(c.pk(c.instance.descriptor.quota),{commitment:'confirmed',minContextSlot});check(r.value&&!r.value.executable&&r.value.owner.toBase58()===c.instance.descriptor.programs.policy,'Wrong quota owner');quota(r.value.data,c.instance.descriptor,c.pk);return r;}
async function checkMxe(c){const mxe=await c.ar.getMXEPublicKey(c.provider,c.program.programId);check(mxe&&Buffer.from(mxe).toString('hex')===c.instance.descriptor.mxePublicKeyHex,'Runtime MXE domain changed');return mxe;}
async function createAccount(c,dir,name,key,space,program){return sendSetup(c,dir,name,[c.w.SystemProgram.createAccount({fromPubkey:c.payer.publicKey,newAccountPubkey:key.publicKey,space,lamports:await c.rpc.getMinimumBalanceForRentExemption(space),programId:c.pk(program)})],[key]);}
async function nativePreparation(c,o,dir){
  const preparationStarted=Date.now();
  const provisionedDir=local(o['provisioned-directory']??c.instance.assetDirectories.license),v=await read(resolve(provisionedDir,'provisioned.json'));
  check(v.evidence_level==='real-local-validator-signed-native-provisioning'&&new URL(v.rpc).href===new URL(c.instance.endpoint).href,'Require same local native provisioning');
  check(c.owner.publicKey.toBase58()===v.source_owner,'Explicit source owner does not match native asset');
  const source=(await c.rpc.getAccountInfo(c.pk(v.accounts.source.address),'confirmed'));check(source&&source.owner.toBase58()===TOKEN,'Wrong native source owner');await save(resolve(dir,'current-source-account.bin'),source.data);
  const contexts={};for(const name of ['equality','grouped','range']){contexts[name]=c.w.Keypair.generate();await save(resolve(dir,`${name}-context-signer.json`),[...contexts[name].secretKey]);}
  const request={source:v.accounts.source.address,mint:v.accounts.mint.address,destination:v.accounts.destination.address,owner:v.source_owner,amount:Number(o.amount),destination_elgamal_pubkey:v.destination_elgamal_pubkey,...Object.fromEntries(Object.entries(contexts).map(([k,s])=>[k,s.publicKey.toBase58()]))};
  await save(resolve(dir,'request.json'),request);
  // Shared pinned upstream-native SDK7 bridge; exposes amount/opening. No CyperLink JS proof/session imports.
  const proofStarted=Date.now();
  await execute(resolve(c.instance.proofCli),['prepare-transfer','--keys',resolve(provisionedDir,'source-confidential.bin'),'--request',resolve(dir,'request.json'),'--source-account',resolve(dir,'current-source-account.bin'),'--output',resolve(dir,'prepared-transfer.json'),'--witness',resolve(dir,'operation-witness.json')],{maxBuffer:1024*1024});
  const proofGenerated=Date.now();
  await chmod(resolve(dir,'prepared-transfer.json'),0o600);
  const p=await read(resolve(dir,'prepared-transfer.json'));check(p.native_verification_required===true&&p.proofs.length===3&&p.source_data_sha256===hash(source.data).toString('hex')&&p.owner===request.owner,'Invalid native preparation output');
  for(const proof of p.proofs){const key=contexts[proof.name],ix=decodeIx(proof.verify_instruction,c.w),raw=hx(proof.proof_data);check(key&&key.publicKey.toBase58()===proof.context_address&&ix.programId.toBase58()===PROOF&&ix.keys.length===2&&ix.keys[0].pubkey.equals(key.publicKey)&&ix.data.subarray(1).equals(raw),'Native proof wire mismatch');await createAccount(c,dir,`proof-create-${proof.name}`,key,proof.context_account_size,PROOF);
    if(raw.length<=800){await sendSetup(c,dir,`proof-verify-${proof.name}`,[ix]);continue;}
    check(raw.length<=16384,'Proof upload too large');const buffer=c.w.Keypair.generate();await save(resolve(dir,`${proof.name}-buffer-signer.json`),[...buffer.secretKey]);await createAccount(c,dir,'proof-buffer',buffer,raw.length,c.instance.descriptor.programs.proofBuffer);
    for(let at=0;at<raw.length;at+=700){const data=Buffer.alloc(5);data.writeUInt32LE(at,1);await sendSetup(c,dir,`proof-upload-${at}`,[new c.w.TransactionInstruction({programId:c.pk(c.instance.descriptor.programs.proofBuffer),keys:[{pubkey:buffer.publicKey,isSigner:true,isWritable:true}],data:Buffer.concat([data,raw.subarray(at,at+700)])})],[buffer]);}
    const uploaded=await c.rpc.getAccountInfo(buffer.publicKey);check(uploaded?.owner.toBase58()===c.instance.descriptor.programs.proofBuffer&&uploaded.data.equals(raw),'Proof buffer mismatch');
    const data=Buffer.alloc(5);data[0]=ix.data[0];await sendSetup(c,dir,`proof-verify-${proof.name}`,[new c.w.TransactionInstruction({programId:ix.programId,data,keys:[{pubkey:buffer.publicKey,isSigner:false,isWritable:false},...ix.keys]})]);
    await sendSetup(c,dir,'proof-buffer-close',[new c.w.TransactionInstruction({programId:c.pk(c.instance.descriptor.programs.proofBuffer),data:Buffer.from([1]),keys:[{pubkey:buffer.publicKey,isSigner:true,isWritable:true},{pubkey:c.payer.publicKey,isSigner:false,isWritable:true}]})],[buffer]);
  }
  await save(resolve(dir,'native-timing.json'),{classification:'internal-local-wall-observation',nativeProofGenerationMs:proofGenerated-proofStarted,proofContextProvisioningVerificationMs:Date.now()-proofGenerated,totalNativePreparationMs:Date.now()-preparationStarted});
  return p;
}
export async function prepare(c,o,dir){
  await mkdir(dir,{mode:0o700});await privateDir(dir);const d=c.instance.descriptor,qr=await readQuota(c),initial=quota(qr.value.data,d,c.pk);
  check(initial.admin===c.payer.publicKey.toBase58(),'Explicit administrator required');const mxe=await checkMxe(c),p=await nativePreparation(c,o,dir),{pk}=c,owner=c.owner.publicKey.toBase58();
  const effect=c.pda(pk(d.programs.license),Buffer.from('license'),pk(owner).toBuffer(),hx(o.product));
  const old=await c.rpc.getAccountInfo(effect);if(!old||(old.owner.equals(c.w.SystemProgram.programId)&&old.data.length===0))await sendSetup(c,dir,'license-initialize',[new c.w.TransactionInstruction({programId:pk(d.programs.license),data:Buffer.concat([Buffer.from([0]),hx(o.product)]),keys:[{pubkey:c.payer.publicKey,isSigner:true,isWritable:true},{pubkey:c.owner.publicKey,isSigner:true,isWritable:false},{pubkey:effect,isSigner:false,isWritable:true},{pubkey:c.w.SystemProgram.programId,isSigner:false,isWritable:false}]})],[c.owner]);else check(!old.executable&&old.owner.toBase58()===d.programs.license&&old.data.length===81&&old.data.every(x=>x===0),'License already issued');
  const native=await c.rpc.getMultipleAccountsInfoAndContext([pk(p.source),...p.proofs.map(x=>pk(x.context_address))],{commitment:'confirmed'}),[source,...proofs]=native.value;
  check(source?.owner.toBase58()===TOKEN&&hash(source.data).toString('hex')===p.source_data_sha256&&proofs.every(x=>x?.owner.toBase58()===PROOF),'Native snapshot changed');
  const t=template(p,source.data,proofs.map(x=>x.data),d,owner,o.product,o['expiry-slot'],effect.toBase58(),pk),permit=c.w.Keypair.generate();await save(resolve(dir,'permit-signer.json'),[...permit.secretKey]);await createAccount(c,dir,'permit-create',permit,712,d.programs.policy);
  const actionId=new c.BN(randomBytes(8),'le'),action=c.pda(c.program.programId,Buffer.from('action'),pk(owner).toBuffer(),actionId.toArrayLike(Buffer,'le',8));
  await sendSetup(c,dir,'prepare-action',[await c.program.methods.prepareAction(actionId,t,hx(p.native_instruction.data)).accounts({payer:c.payer.publicKey,sourceOwner:c.owner.publicKey,action}).instruction()],[c.owner]);
  const secret=c.ar.x25519.utils.randomSecretKey(),pub=c.ar.x25519.getPublicKey(secret),cipher=new c.ar.CSplRescueCipher(c.ar.x25519.getSharedSecret(secret,mxe)),witness=await read(resolve(dir,'operation-witness.json'));
  check(witness.amount===Number(o.amount)&&Buffer.from(witness.commitment).toString('hex')===p.expected_commitment,'Native witness amount/commitment differs');const nonce=randomBytes(16),encrypted=cipher.encrypt([BigInt(o.amount),c.ar.deserializeLE(Uint8Array.from(witness.opening))],nonce);secret.fill(0);
  const current=await readQuota(c,native.context.slot),before=current.value.data,q=quota(before,d,pk);check(q.admin===initial.admin,'Administrator changed');const queued=Buffer.alloc(712),expiry=String(current.context.slot+1800);t.copy(queued);before.subarray(0,8).copy(queued,8);before.subarray(8,40).copy(queued,16);le(q.counter+1n,16).copy(queued,464);le(expiry).copy(queued,512);before.subarray(257).copy(queued,616);
  const plan={schema:'direct-license-v1',deployment:d,genesis:d.genesisHash,label:o.label,owner,admin:c.payer.publicKey.toBase58(),product:o.product,expiry:o['expiry-slot'],effect:effect.toBase58(),permit:permit.publicKey.toBase58(),action:action.toBase58(),contextSlot:current.context.slot,native:p,sourceData:source.data.toString('hex'),proofData:proofs.map(x=>x.data.toString('hex')),quotaSnapshot:before.toString('hex'),queuedTemplate:queued.toString('hex'),query:{offset:new c.BN(randomBytes(8),'le').toString(),expiry,publicKey:Buffer.from(pub).toString('hex'),nonce:nonce.toString('hex'),amount:Buffer.from(encrypted[0]).toString('hex'),opening:Buffer.from(encrypted[1]).toString('hex')},inputsHash:hash(pub,nonce,encrypted[0],encrypted[1],before.subarray(40,56),q.ciphertexts,le(q.counter+1n,16),hx(p.expected_commitment),before.subarray(257)).toString('hex')};
  const a=accountsFor(c,plan);plan.job=a.job.toBase58();plan.computation=a.computationAccount.toBase58();validatePlan(c,plan);await save(resolve(dir,'operation.json'),plan);return {status:'prepared',paymentCommitted:false,operation:dir};
}
export async function observe(c,p,dir,minSlot=p.contextSlot){validatePlan(c,p);check(await c.rpc.getGenesisHash()===p.genesis,'Observation ledger changed');const history=resolve(dir,'observations');await privateDir(history);const {readdir}=await import('node:fs/promises');for(const name of await readdir(history)){if(name.endsWith('.json'))minSlot=Math.max(minSlot,(await read(resolve(history,name))).slot??0);}const r=await c.rpc.getMultipleAccountsInfoAndContext([p.job,p.permit,p.deployment.quota,p.effect].map(c.pk),{commitment:'confirmed',minContextSlot:minSlot});check(r.context.slot>=minSlot,'Regressed observation context');const result=reconcile(c,p,r);await save(resolve(history,`${randomUUID()}.json`),{...result,accounts:r.value.map(a=>a?{owner:a.owner.toBase58(),executable:a.executable,data:a.data.toString('base64')}:null)});return result;}
export async function main(args=process.argv.slice(2)){
  const {command,o}=parse(args),instance=await read(local(o.instance)),dir=local(o.operation),c=await connect(instance,{adminPath:o['admin-keyfile'],ownerPath:o['owner-keyfile']});
  if(command==='prepare')return prepare(c,o,dir);
  const p=await read(resolve(dir,'operation.json'));validatePlan(c,p);if(command==='observe')return observe(c,p,dir);
  const role=command==='recover'?o.role:command==='approve-query'?'query':'commit',path=resolve(dir,`${role}-wire.json`),ix=role==='query'?await queryIx(c,p):commitIx(c,p),planHash=digest(p);
  if(role==='query')await assertPreparedAction(c,p);
  if(command!=='recover'){check(c.payer.publicKey.toBase58()===p.admin&&c.owner.publicKey.toBase58()===p.owner,'Explicit signer mismatch');if(!await exists(path)){const lock=resolve(dir,`${role}-approval.lock`),intent=resolve(dir,`${role}-approval-intent.json`);check(!await exists(intent),'Interrupted approval intent exists; no automatic restaging');await mkdir(lock,{mode:0o700});await save(intent,{role,planHash,owner:p.owner,admin:p.admin});try{check(!await exists(path),'Concurrent approval created wire; reopen operation');if(role==='query'){const q=await readQuota(c,p.contextSlot);check(hash(q.value.data).equals(hash(hx(p.quotaSnapshot))),'Query state changed; fresh explicit preparation required');await checkMxe(c);}else check((await observe(c,p,dir)).status==='authorized','Payment requires current authorization');await stage(c,path,[ix],[c.owner],{role,planHash,minSlot:p.contextSlot});}finally{await rmdir(lock);}}}
  const retainedIntent=await read(resolve(dir,`${role}-approval-intent.json`));check(digest(retainedIntent)===digest({role,planHash,owner:p.owner,admin:p.admin}),'Approval intent mismatch');const record=await read(path);check(record.role===role&&record.payer===p.admin&&record.storagePath===path&&record.expectedError===undefined,'Wrong wire role/payer/storage');validateWire(c,record,budgeted(c,[ix]),planHash);
  if(o.submit==='no'&&command!=='recover'){const simulation=await exists(path+'.simulation.json')?await read(path+'.simulation.json'):null;return {status:simulation?(Number.isSafeInteger(simulation.context?.slot)&&simulation.context.slot>=record.minSlot&&simulation.value?.err===null&&simulation.directBinding?.signature===record.signature&&simulation.directBinding?.wireSha256===hash(Buffer.from(record.wire,'base64')).toString('hex')?'signed-not-submitted':'signed-simulation-rejected'):'signed-needs-simulation',paymentCommitted:false,signature:record.signature,wire:path};}
  const delivery=await recover(c,record,budgeted(c,[ix]),planHash,{submit:command==='recover'?o.submit==='yes':true,poll:command==='recover'&&o.submit!=='yes'?1:100});
  await save(resolve(dir,`${role}-recovery-${randomUUID()}.json`),delivery);const observation=await observe(c,p,dir,Math.max(p.contextSlot,delivery.slot??0));return {...observation,deliveryStatus:delivery.status,signature:record.signature,delivery};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().then(r=>console.log(JSON.stringify(r,null,2))).catch(e=>{console.error(JSON.stringify({status:'unresolved',paymentCommitted:false,error:e.message}));process.exitCode=1;});
