import test, { after } from 'node:test';
import { mkdirSync, writeFileSync, rmSync, readdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { hash } from './abi.mjs';
import { parse } from './app.mjs';
import { validateWire, recover, budgeted } from './wire.mjs';
const testRoot=resolve('.local','direct-license-tests-'+randomUUID());mkdirSync(testRoot,{mode:0o700});after(()=>rmSync(testRoot,{recursive:true,force:true}));
const require=createRequire(resolve('.local/toolchain/js/package.json')),w=require('@solana/web3.js'),bs=require('bs58'),bs58=bs.default??bs;
function fixture(){const payer=w.Keypair.generate(),dest=w.Keypair.generate(),blockhash=w.Keypair.generate().publicKey.toBase58(),genesis=w.Keypair.generate().publicKey.toBase58();const c={w,bs58,pk:x=>new w.PublicKey(x),instance:{descriptor:{genesisHash:genesis}}};const ixs=budgeted(c,[w.SystemProgram.transfer({fromPubkey:payer.publicKey,toPubkey:dest.publicKey,lamports:1})]),tx=new w.VersionedTransaction(new w.TransactionMessage({payerKey:payer.publicKey,recentBlockhash:blockhash,instructions:ixs}).compileToV0Message());tx.sign([payer]);const record={storagePath:resolve(testRoot,randomUUID()+'.json'),schema:'direct-wire-v1',role:'commit',genesis,planHash:'plan',payer:payer.publicKey.toBase58(),signature:bs58.encode(tx.signatures[0]),wire:Buffer.from(tx.serialize()).toString('base64'),tables:[],minSlot:7,blockhash:{blockhash,lastValidBlockHeight:10}};writeFileSync(record.storagePath,JSON.stringify(record),{mode:0o600});writeFileSync(record.storagePath+'.simulation.json',JSON.stringify({context:{slot:8},value:{err:null},directBinding:{signature:record.signature,wireSha256:hash(Buffer.from(record.wire,'base64')).toString('hex')}}),{mode:0o600});return {c,record,ixs,tx};}
test('explicit signing paths and strict amounts/options',()=>{assert.throws(()=>parse(['prepare','--instance','i','--operation','o']),/Explicit/);assert.throws(()=>parse(['observe','--instance','i','--operation','o','--submit','yes']),/Submit invalid/);assert.throws(()=>parse(['recover','--instance','i','--operation','o']),/role/);});
test('exact message signatures and operation binding reject mutation',()=>{const {c,record,ixs}=fixture();validateWire(c,record,ixs,'plan');assert.throws(()=>validateWire(c,record,ixs,'another'),/operation mismatch/);const wire=Buffer.from(record.wire,'base64');wire[5]^=1;assert.throws(()=>validateWire(c,{...record,wire:wire.toString('base64')},ixs,'plan'),/Signature identity|Ed25519/);assert.throws(()=>validateWire(c,record,ixs.slice(0,1),'plan'),/instructions differ/);});
test('expiry without receipt remains unresolved and never broadcasts replacement',async()=>{const {c,record,ixs}=fixture();let sends=0;c.rpc={getGenesisHash:async()=>record.genesis,getTransaction:async()=>null,getSignatureStatuses:async()=>({context:{slot:8},value:[null]}),getBlockHeight:async()=>11,sendRawTransaction:async()=>{sends++;}};const r=await recover(c,record,ixs,'plan',{submit:true});assert.equal(r.status,'expired-unresolved');assert.equal(sends,0);});
test('receipt loss preserves exact retransmission and does not report payment',async()=>{const {c,record,ixs}=fixture();let sent;c.rpc={getGenesisHash:async()=>record.genesis,getTransaction:async()=>{throw Error('receipt unavailable');},getSignatureStatuses:async()=>({context:{slot:8},value:[null]}),getBlockHeight:async()=>9,isBlockhashValid:async()=>({context:{slot:8},value:true}),sendRawTransaction:async b=>{sent=Buffer.from(b);throw Error('ack lost');}};const r=await recover(c,record,ixs,'plan',{submit:true});assert.equal(r.status,'pending');assert.equal(sent.toString('base64'),record.wire);assert.equal(r.sendError,'ack lost');});
test('status without receipt cannot establish confirmation and prevents unnecessary resend',async()=>{const {c,record,ixs}=fixture();c.rpc={getGenesisHash:async()=>record.genesis,getTransaction:async()=>null,getSignatureStatuses:async()=>({context:{slot:8},value:[{confirmationStatus:'confirmed'}]}),getBlockHeight:async()=>9,isBlockhashValid:async()=>({context:{slot:8},value:true}),sendRawTransaction:async()=>assert.fail('must not resend')};assert.equal((await recover(c,record,ixs,'plan',{submit:true})).status,'receipt-unavailable');});
test('receipt must contain the retained message and all signatures',async()=>{const {c,record,ixs,tx}=fixture();c.rpc={getGenesisHash:async()=>record.genesis,getTransaction:async()=>({slot:9,meta:{err:null},transaction:{message:tx.message,signatures:[w.Keypair.generate().publicKey.toBase58()]}})};await assert.rejects(recover(c,record,ixs,'plan'),/receipt differs/);});

test('three durable broadcast attempts survive independent recovery calls',async()=>{const {c,record,ixs}=fixture();let sends=0;c.rpc={getGenesisHash:async()=>record.genesis,getTransaction:async()=>null,getSignatureStatuses:async()=>({context:{slot:8},value:[null]}),getBlockHeight:async()=>9,isBlockhashValid:async()=>({context:{slot:8},value:true}),sendRawTransaction:async()=>{sends++;throw Error('lost response');}};for(let i=0;i<4;i++)await recover(c,record,ixs,'plan',{submit:true});assert.equal(sends,3);assert.equal(readdirSync(record.storagePath+'.attempts').filter(x=>x.startsWith('attempt-')).length,3);});
test('missing simulation is safely recreated for the identical signed wire',async()=>{const {c,record,ixs,tx}=fixture();rmSync(record.storagePath+'.simulation.json');let sims=0,sends=0;c.rpc={getGenesisHash:async()=>record.genesis,getTransaction:async()=>null,getSignatureStatuses:async()=>({context:{slot:8},value:[null]}),getBlockHeight:async()=>9,isBlockhashValid:async()=>({context:{slot:8},value:true}),simulateTransaction:async t=>{sims++;assert(Buffer.from(t.serialize()).equals(Buffer.from(tx.serialize())));return {context:{slot:8},value:{err:null}};},sendRawTransaction:async()=>{sends++;return record.signature;}};await recover(c,record,ixs,'plan',{submit:true});assert.equal(sims,1);assert.equal(sends,1);});
test('invalid blockhash and failed simulations prevent broadcasts',async()=>{const {c,record,ixs}=fixture();let sends=0;c.rpc={getGenesisHash:async()=>record.genesis,getTransaction:async()=>null,getSignatureStatuses:async()=>({context:{slot:8},value:[null]}),getBlockHeight:async()=>9,isBlockhashValid:async()=>({context:{slot:8},value:false}),sendRawTransaction:async()=>{sends++;}};await recover(c,record,ixs,'plan',{submit:true});assert.equal(sends,0);c.rpc.isBlockhashValid=async()=>({context:{slot:8},value:true});writeFileSync(record.storagePath+'.simulation.json',JSON.stringify({context:{slot:8},value:{err:'failure'}}));await recover(c,record,ixs,'plan',{submit:true});assert.equal(sends,0);});
