#!/usr/bin/env node
// Qualification harness only. Shared deployment, ELF verifier, snapshot/archive
// helpers and fault-preload protocol are explicitly excluded from independent app work.
import assert from 'node:assert/strict';
import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { connect } from './app.mjs';
import { hash, hx, digest, commitIx, quota } from './abi.mjs';
import { stage, recover, budgeted, wait } from './wire.mjs';
import { snapshot, unchanged, businessState, callback } from '../policies/qualification/evidence.mjs';
import { signedMessage } from '../policies/qualification/archive.mjs';
const execute=promisify(execFile),[instancePath,output]=process.argv.slice(2),ROOT=resolve('.'),directory=resolve(output),json=async p=>JSON.parse(await readFile(p));
assert(instancePath&&output&&directory.startsWith(resolve('.local')+'/'));await mkdir(directory,{mode:0o700});
const instance=await json(instancePath),c=await connect(instance,{adminPath:instance.payerKeyfile,ownerPath:resolve(instance.assetDirectories.license,'source-owner-signer.json')}),rpc=c.rpc;
const result={schema:1,passed:false,classification:'direct-client-shared-cyperlink-enforcement-real-local',startedAt:new Date().toISOString(),deployment:instance.descriptor,instancePath:resolve(instancePath),observerDisclosures:{remaining:50,purchase_cap:30,amounts:[40,30,30,30,20]},appInvocations:[],callbacks:[],transactions:[],accountSnapshots:[],operations:[],checks:[],loadedPrograms:[],limitations:['Client comparison shares CyperLink enforcement, compiler/circuit, native proof CLI and deployment/native funding','Internal author source assistance, not human productivity/external developer validation','One local validator and two local Arcium nodes, same operator','Confirmed RPC evidence, no independent offline BLS or consensus proof','Fault preload and archive verification are shared harness utilities; not application implementation','Full standalone upstream comparison is inconclusive']};
const save=()=>writeFile(resolve(directory,'results.json'),JSON.stringify(result,(_,v)=>typeof v==='bigint'?v.toString():v,2),{mode:0o600});await save();
try{
 const sourceFiles=['abi.mjs','app.mjs','wire.mjs','crash-preload.mjs','qualify.mjs','rpc-fault.mjs'];await mkdir(resolve(directory,'executed-source'),{mode:0o700});result.executedClientSources=[];for(const name of sourceFiles){const bytes=await readFile(resolve('examples/license-direct',name));await writeFile(resolve(directory,'executed-source',name),bytes,{mode:0o600});result.executedClientSources.push({path:'examples/license-direct/'+name,sha256:hash(bytes).toString('hex')});}await save();
 const deployment=await json(instance.results);assert(deployment.passed);
 for(const [i,program]of deployment.loadedPrograms.entries()){const file=resolve(directory,`loaded-${i}.json`);await execute('python3',['scripts/verify_loaded_program.py','--program-id',program.program,'--elf',program.local_elf_path,'--rpc',instance.endpoint,'--output',file]);const proof=await json(file);assert(proof.matched);result.loadedPrograms.push(proof);}assert.equal(result.loadedPrograms.length,10);await save();
 async function app(command,op,extra=[],fault,crash,expectedFailure=false){const args=['examples/license-direct/app.mjs',command,'--instance',resolve(instancePath),'--operation',op.directory,...extra];if(['prepare','approve-query','approve-payment'].includes(command))args.push('--admin-keyfile',instance.payerKeyfile,'--owner-keyfile',op.ownerPath);const started=Date.now();let stdout='',stderr='',code=0,signal=null;try{({stdout,stderr}=await execute(process.execPath,args,{maxBuffer:16*1024*1024,env:{...process.env,...(crash?{CYPERLINK_DIRECT_CRASH_FILE:crash,NODE_OPTIONS:`${process.env.NODE_OPTIONS??''} --import=${pathToFileURL(resolve('examples/license-direct/crash-preload.mjs')).href}`} : {}),...(fault?{CYPERLINK_TEST_RPC_FAULT_FILE:fault,NODE_OPTIONS:`${process.env.NODE_OPTIONS??''} --import=${pathToFileURL(resolve('examples/license-direct/rpc-fault.mjs')).href}`}:{})}}));}catch(e){stdout=e.stdout??'';stderr=e.stderr??'';code=e.code;signal=e.signal;}let summary;try{summary=JSON.parse(code?stderr.trim().split('\n').at(-1):stdout);}catch{summary={parseError:true,stdout,stderr};}const id=result.appInvocations.length;await writeFile(resolve(directory,`invocation-${id}.json`),JSON.stringify({args,stdout,stderr,code,signal}),{mode:0o600});result.appInvocations.push({command,label:op.label,exitCode:code,signal,elapsedMs:Date.now()-started,faultInjected:Boolean(fault),summary});await save();if(crash){assert.equal(signal,'SIGKILL',stderr);return {signal,invocation:id};}if(expectedFailure){assert.notEqual(code,0);return {...summary,exitCode:code,invocation:id};}assert.equal(code,0,stderr);return summary;}
 async function prepare(label,amount,source='license'){const assets=instance.assetDirectories[source],op={label,amount,directory:resolve(directory,'operation-'+label),ownerPath:resolve(assets,'source-owner-signer.json')};await app('prepare',op,['--label',label,'--amount',String(amount),'--product',hash(Buffer.from(label)).toString('hex'),'--expiry-slot',String(await rpc.getSlot('confirmed')+950),'--provisioned-directory',assets]);op.plan=await json(resolve(op.directory,'operation.json'));result.operations.push({label,amountObserverDisclosure:amount,planPath:resolve(op.directory,'operation.json')});await save();return op;}
 const tracked=op=>[op.plan.native.source,op.plan.native.destination,op.plan.native.mint,...op.plan.native.proofs.map(x=>x.context_address),op.plan.deployment.quota,op.plan.permit,op.plan.effect,op.plan.job,op.plan.computation,op.plan.action].map(c.pk);
 const snap=(op,label)=>snapshot(rpc,tracked(op),label,result,save);
 const account=(s,key)=>Buffer.from(s.accounts.find(a=>a.address===key).dataBase64,'base64');
 async function artifacts(op,role){const path=resolve(op.directory,role+'-wire.json'),value={directoryEntries:(await readdir(op.directory)).sort(),attemptEntries:[],wire:null,simulation:null};try{value.wire=await json(path);value.wireFileSha256=hash(await readFile(path)).toString('hex');value.wireSha256=hash(Buffer.from(value.wire.wire,'base64')).toString('hex');}catch(e){if(e.code!=='ENOENT')throw e;}try{value.simulation=await json(path+'.simulation.json');}catch(e){if(e.code!=='ENOENT')throw e;}try{value.attemptEntries=(await readdir(path+'.attempts')).sort();}catch(e){if(e.code!=='ENOENT')throw e;}return value;}
 async function interrupted(op,role,phase){const label=op.label+'-'+role+'-'+phase,target=resolve(op.directory,role+'-wire.json'+(phase==='after-simulation'?'.simulation.json':'')),config=resolve(directory,label+'-crash.json'),log=resolve(directory,label+'-crash.ndjson');await writeFile(config,JSON.stringify({target,phase,log}),{mode:0o600});const before=await snap(op,label+'-before');const stopped=await app(role==='query'?'approve-query':'approve-payment',op,['--submit','no'],undefined,config);const beforeRecovery=await artifacts(op,role),marker=(await readFile(log,'utf8')).trim().split('\n').map(JSON.parse);assert.equal(marker.length,1);assert.equal(beforeRecovery.attemptEntries.length,0);if(phase==='before-wire')assert.equal(beforeRecovery.wire,null);else{assert(beforeRecovery.wire);assert.equal(Boolean(beforeRecovery.simulation),phase==='after-simulation');}
 let readonly,repeatRefusal;if(phase!=='before-wire')readonly=await app('recover',op,['--role',role]);else{readonly=await app('recover',op,['--role',role],undefined,undefined,true);repeatRefusal=await app('approve-query',op,['--submit','no'],undefined,undefined,true);assert.match(repeatRefusal.error,/Interrupted approval intent/);}const afterReadonlyRecovery=await artifacts(op,role);assert.equal(afterReadonlyRecovery.wireFileSha256,beforeRecovery.wireFileSha256);assert.deepEqual(afterReadonlyRecovery.attemptEntries,beforeRecovery.attemptEntries);assert.deepEqual(afterReadonlyRecovery.simulation,beforeRecovery.simulation);const after=await snap(op,label+'-readonly-after');unchanged(before,after);const entry={label,role,phase,signal:stopped.signal,invocation:stopped.invocation,markerPath:log,marker,beforeSnapshot:before.label,afterReadonlySnapshot:after.label,beforeRecovery,afterReadonlyRecovery,readonlyOutcome:readonly??null,repeatRefusal:repeatRefusal??null,planPath:resolve(op.directory,'operation.json')};(result.crashWindows??=[]).push(entry);await save();return entry;}
 async function admit(op,allowed){const before=await snap(op,op.label+'-query-before'),started=Date.now();if(op.label==='a30'||op.label==='competing30'){const crash=await interrupted(op,'query',op.label==='a30'?'after-wire':'after-simulation');await app('recover',op,['--role','query','--submit','yes']);crash.afterSubmission=await artifacts(op,'query');assert.equal(crash.beforeRecovery.wireFileSha256,crash.afterSubmission.wireFileSha256);await save();}else await app('approve-query',op);const adapter={program:c.program,session:{web3:c.w,connection:rpc}},adapted={label:op.label,plan:{descriptor:{job:op.plan.job,computation:op.plan.computation}}};const cb=await callback(adapter,adapted,allowed?1:2,started,result,save);assert.equal(cb.result.output.field1,allowed);assert(Buffer.from(cb.result.output.field0).equals(hx(op.plan.native.expected_commitment)));const after=await snap(op,op.label+'-callback-after');assert(businessState(account(before,op.plan.deployment.quota)).equals(businessState(account(after,op.plan.deployment.quota))));const observed=await app('observe',op);assert.equal(observed.status,allowed?'authorized':'denied');assert.equal(observed.paymentCommitted,false);if(allowed){const p=account(after,op.plan.permit),out=cb.result.output.field2;assert(p.subarray(480,512).equals(Buffer.from(out[0]))&&p.subarray(520,616).equals(Buffer.concat(out.slice(1).map(x=>Buffer.from(x)))));}result.checks.push({label:op.label+'-decision',allowed,callbackDoesNotPay:true});await save();return op;}
 async function rejection(op,label,error,postNative=false){const owner=c.w.Keypair.fromSecretKey(Uint8Array.from(await json(op.ownerPath))),ix=commitIx(c,op.plan);if(postNative)ix.data[41]=1;const before=await snap(op,label+'-before'),file=resolve(directory,label+'-wire.json'),r=await stage(c,file,[ix],[owner],{role:label,planHash:digest(op.plan),minSlot:op.plan.contextSlot,expectedError:error});const delivered=await recover(c,r,budgeted(c,[ix]),digest(op.plan),{submit:true,poll:100});assert.equal(delivered.status,'rejected');assert.equal(delivered.receipt.meta.err.InstructionError[1].Custom,error);if(postNative)assert(delivered.receipt.meta.logMessages.some(x=>x.includes('ConfidentialTransferInstruction::Transfer')));unchanged(before,await snap(op,label+'-after'));result.transactions.push({label,category:'adversarial-landed-failure',signature:r.signature,slot:delivered.slot,transaction:delivered.receipt,landedCU:delivered.receipt.meta.computeUnitsConsumed,feeLamports:delivered.receipt.meta.fee});result.checks.push({label,expectedError:error,unchangedAccounts:before.accounts.length,postNative});await save();}
 async function paid(op,lostAck){const before=await snap(op,op.label+'-payment-before');if(op.label==='a30'||op.label==='fresh-b20')await interrupted(op,'commit',op.label==='a30'?'after-simulation':'after-wire');else await app('approve-payment',op,['--submit','no']);const file=resolve(op.directory,'commit-wire.json'),r=await json(file),wireHash=hash(await readFile(file)).toString('hex');if(lostAck){for(const mode of ['lost-ack','unavailable-receipt']){const config=resolve(directory,mode+'.json'),log=resolve(directory,mode+'.ndjson');await writeFile(config,JSON.stringify({mode,endpoint:instance.endpoint,signature:r.signature,wireSha256:hash(Buffer.from(r.wire,'base64')).toString('hex'),log}),{mode:0o600});const observed=await app(mode==='lost-ack'?'approve-payment':'recover',op,mode==='lost-ack'?[]:['--role','commit'],config);assert.equal(observed.deliveryStatus,'receipt-unavailable');const events=(await readFile(log,'utf8')).trim().split('\n').map(JSON.parse);assert(events.some(e=>e.fault==='receipt-unavailable'));assert.equal(events.filter(e=>e.fault==='actual-send-response-lost').length,mode==='lost-ack'?1:0);(result.injectedFaults??=[]).push({mode,events,paymentObservedIndependently:observed.paymentCommitted});await save();}}else await app('recover',op,['--role','commit','--submit','yes']);
 const final=await app('recover',op,['--role','commit']);assert.equal(final.status,'committed');assert.equal(final.deliveryStatus,'confirmed');assert.equal(final.signature,r.signature);assert.equal(hash(await readFile(file)).toString('hex'),wireHash);const crash=result.crashWindows?.find(x=>x.label===op.label+'-commit-'+(op.label==='a30'?'after-simulation':'after-wire'));if(crash){crash.afterSubmission=await artifacts(op,'commit');assert.equal(crash.beforeRecovery.wireFileSha256,crash.afterSubmission.wireFileSha256);}const after=await snap(op,op.label+'-payment-after'),pb=account(after,op.plan.permit),qb=account(after,op.plan.deployment.quota),eb=account(after,op.plan.effect);assert.equal(pb[0],2);assert.equal(qb.readBigUInt64LE(),account(before,op.plan.deployment.quota).readBigUInt64LE()+1n);assert(qb.subarray(8,40).equals(pb.subarray(48,80)));for(const key of [op.plan.native.source,op.plan.native.destination])assert(!account(before,key).equals(account(after,key)));assert.equal(eb.subarray(40,72).toString('hex'),op.plan.product);assert.equal(eb.readBigUInt64LE(72).toString(),op.plan.expiry);const tx=final.delivery.receipt;assert(tx.meta.logMessages.includes(`Program ${TOKEN} success`));result.transactions.push({label:op.label+'-paid',category:'native-settlement',signature:r.signature,slot:tx.slot,transaction:tx,landedCU:tx.meta.computeUnitsConsumed,feeLamports:tx.meta.fee});result.checks.push({label:op.label+'-paid-license',signature:r.signature,lostAck,exactRetainedWire:true,keylessNewProcess:true,quotaAndNativeAccountsChanged:true});await save();}
 const TOKEN='TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
 await admit(await prepare('cap40',40),false);const a=await admit(await prepare('a30',30),true);const repeat=await snap(a,'repeat-before');await app('approve-query',a);unchanged(repeat,await snap(a,'repeat-after'));result.checks.push({label:'repeat-query-exact-wire-no-new-query'});
 const b=await admit(await prepare('competing30',30,'merchant'),true);await rejection(a,'post-native-rollback',1199,true);await paid(a,true);assert.equal((await app('observe',b)).status,'stale');await rejection(b,'stale803',803);await rejection(a,'replay1102',1102);await admit(await prepare('fresh-b30',30,'merchant'),false);const fresh=await admit(await prepare('fresh-b20',20,'merchant'),true);await paid(fresh,false);
 const interruptedOnly=await prepare('before-wire-unsubmitted',1,'merchant');result.operations.pop();result.interruptedOperation={label:interruptedOnly.label,planPath:resolve(interruptedOnly.directory,'operation.json')};await interrupted(interruptedOnly,'query','before-wire');
 result.tickets=[];for(const op of result.operations){const p=await json(op.planPath),dir=dirname(op.planPath);for(const role of ['query','commit']){let r;try{r=await json(resolve(dir,role+'-wire.json'));}catch(e){if(e.code==='ENOENT')continue;throw e;}const tx=await rpc.getTransaction(r.signature,{commitment:'confirmed',maxSupportedTransactionVersion:0});assert(tx&&!tx.meta.err);const expected=c.w.VersionedTransaction.deserialize(Buffer.from(r.wire,'base64'));assert(Buffer.from(tx.transaction.message.serialize()).equals(Buffer.from(expected.message.serialize())));result.tickets.push({label:op.label,role,signature:r.signature,wireSha256:hash(Buffer.from(r.wire,'base64')).toString('hex'),exactLandedMessage:true});if(!result.transactions.some(x=>x.signature===r.signature))result.transactions.push({label:op.label+'-'+role,category:role==='query'?'arcium-queue':'native-settlement',signature:r.signature,slot:tx.slot,transaction:tx,landedCU:tx.meta.computeUnitsConsumed,feeLamports:tx.meta.fee});}}
 result.circuitArtifacts=[];for(const name of ['runtime_policy_init','runtime_policy_evaluate'])result.circuitArtifacts.push(await json(resolve(dirname(instancePath),name+'-uploaded-evidence.json')));
 const q=(await rpc.getAccountInfoAndContext(c.pk(instance.descriptor.quota),{commitment:'confirmed'}));assert.equal(quota(q.value.data,instance.descriptor,c.pk).version,2n);result.finalState={slot:q.context.slot,dataBase64:q.value.data.toString('base64')};let signatures=0;const seen=new Set();for(const tx of [...result.transactions,...result.callbacks])if(!seen.has(tx.signature)){seen.add(tx.signature);signatures+=signedMessage(JSON.parse(JSON.stringify(tx)),c.w,c.bs58).signatures;}result.signedArchiveChecks={messages:seen.size,ed25519Signatures:signatures};assert.equal(result.callbacks.length,5);assert.equal(result.tickets.length,7);for(const source of result.executedClientSources)assert.equal(hash(await readFile(source.path)).toString('hex'),source.sha256,'Client source changed during qualification');result.finishedAt=new Date().toISOString();result.passed=true;await save();console.log(JSON.stringify({passed:true,results:resolve(directory,'results.json'),callbacks:5,paidLicenses:2}));
}catch(error){result.error=error.stack;await save();throw error;}
