[package]
name="cyperlink-license"
version="0.1.0"
edition="2021"
[lib]
crate-type=["cdylib","lib"]
[dependencies]
solana-account-info={workspace=true}
solana-address={workspace=true}
solana-program-entrypoint={workspace=true}
solana-program-error={workspace=true}
solana-instruction={workspace=true}
solana-cpi={workspace=true}
solana-sha256-hasher={workspace=true}
cyperlink-operation={path="../interface"}
cyperlink-pda-provisioning={path="../../../crates/pda-provisioning"}
solana-clock="=3.2.1"
solana-sysvar="=3.1.1"
solana-rent="=3.1.0"
solana-system-interface={version="=2.0.0",features=["bincode"]}
