[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cyperlink_auth = "5bgSoi3WbUndQNhWrkxJoURjkRd28BxxucZozwGR9AQQ"

[provider]
cluster = "localnet"
wallet = "../../.local/admin.json"
